import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Sidebar from "@/shared/components/layout/Sidebar";
import Header from "@/shared/components/layout/Header";
import Footer from "@/shared/components/layout/Footer";
import Content from "@/shared/components/layout/Content";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased d-flex h-100`}
      >
        {/* Sidebar fixa */}
        <Sidebar />

        {/* Área da direita */}
        <div className="d-flex flex-column flex-grow-1">
          <Header />
          <Content>{children}</Content>
          <Footer />
        </div>
      </body>
    </html>
  );
}
